# /etc/fail2ban/action.d/feishu.conf
[Definition]

actionunban = python3 /etc/fail2ban/action.d/feishu-ban.py \
              --webhook="<webhook_url>" \
              --secret="<secret>" \
              --jail="<name>" \
              --ip="<ip>" \
              --action="unban"

actionban = python3 /etc/fail2ban/action.d/feishu-ban.py \
              --webhook="<webhook_url>" \
              --secret="<secret>" \
              --jail="<name>" \
              --ip="<ip>" \
              --action="ban"

actionstart = true
actionstop = true

[Init]
webhook_url = https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_WEBHOOK_ID
secret = YOUR_BOT_SECRET
